version : 1

sources : 
  - name: travel_bc
    database: carteldeladata
    schema: travel_bc
    tables:
      - name: car_bookings
      - name: car_rental_companies
      - name: hotel_bookings
      - name: hotel_rooms
      - name: hotels
      - name: users